#!/usr/bin/env perl
use Mojolicious::Lite;
use DBI;
my $cfg = plugin 'Config';

my $dbh;
if ($cfg->{db_driver} eq 'pgsql') {

}
elsif ($cfg->{db_driver} eq 'sqlite') {
}
else {
  die
    "Invalid database driver selected. Did you forget to edit facile.conf?\n";
}

# Documentation browser under "/perldoc"
plugin 'PODRenderer';

get '/' => sub {
  my $self = shift;
  $self->render('index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
Welcome to the Mojolicious real-time web framework!

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
