#!/usr/bin/env perl

#
# facile - Static/Dynamic Content Management System
# Copyright (C) 2014  Aaron W. Swenson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

use Mojolicious::Lite;
use Mojo::Pg;

my $pg = Mojo::Pg->new($ENV{DATABASE_URL}) or app->log->fatal($!);

####################
# Database Helpers #
####################
helper 'db.list_tags' => sub { $pg->db->query(q|SELECT tag FROM tags|) };

helper 'db.list_articles' => sub {
  $pg->db->query(q|SELECT title FROM articles|);
};

helper 'db.article_exists' => sub {
  my ($c, $name) = @_;
  $pg->db->query('SELECT COUNT(*) FROM articles WHERE file_name = ?', $name);
};

helper 'db.has_admin' => sub {
  $pg->db->query('SELECT COUNT(*) FROM authors WHERE admin = TRUE');
};

##########
# Routes #
##########

get '/' => sub {
  my $c = shift;
  $c->render('index');
};

get '/:topdir/#name' => [topdir => [qw(article tag)]] => sub {
  my $c      = shift;
  my $name   = $c->param('name');
  my $topdir = $c->param('topdir');

  $name =~ s|\.{2,}|-|g;
  $name =~ s|^\.+||;

  if ($topdir eq 'article' && $c->db->article_exists($name)) {
    $c->render('article');
  }
  elsif ($topdir eq 'tag' && $c->db->tag_exists($name)) {
    $c->render('tag');
  }
  else {
    $c->render('does_not_exist');
  }
};

under '/admin';

get '/add-post';

get '/setup' => sub {
  my $c = shift;
  if ($pg->migrations->active and $c->db->has_admin) {
    $c->render('admin/setup-done');
  }
  else {
    $pg->migrations->from_file('migrations.sql')->migrate;
    $c->render('admin/setup');
  }
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
% for ($c->db->list_articles) {
Do some magic
% }

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>

@@ tag.atom.ep

@@ tag.html.ep
% layout 'default';
% title 'Tag: ' . $name;
%= $c->db->list_articles_with_tag($name)
